[difit]
fetch.github = "yoshiko-pg/difit"
src.manual = "v2.2.7"

[ghost]
fetch.github = "skanehira/ghost"
src.manual = "v0.3.0"

[jsmigemo]
fetch.url = "https://registry.npmjs.org/jsmigemo/-/jsmigemo-$ver.tgz"
src.manual = "0.4.8"

[rustmigemo]
fetch.github = "oguna/rustmigemo"
src.manual = "v0.1.6"

[kakehashi]
fetch.github = "atusy/kakehashi"
src.manual = "v0.0.10"

[plamo-translate]
fetch.github = "pfnet/plamo-translate-cli"
src.manual = "1.0.5"

[stormy]
fetch.github = "ashish0kumar/stormy"
src.manual = "v0.3.3"

[lolcrab]
fetch.github = "mazznoer/lolcrab"
src.manual = "v0.4.1"

[rxpipes]
fetch.github = "inunix3/rxpipes"
src.manual = "v1.3.0"

