[difit]
fetch.github = "yoshiko-pg/difit"
src.manual = "v3.0.0"

[ghost]
fetch.github = "skanehira/ghost"
src.manual = "v0.3.0"

[jsmigemo]
fetch.url = "https://registry.npmjs.org/jsmigemo/-/jsmigemo-$ver.tgz"
src.manual = "0.4.8"

# Fork with aarch64 fix (manual update until merged upstream)
[rustmigemo]
fetch.github = "kawarimidoll/rustmigemo"
fetch.branch = "fix-build-error-in-non-x86"
src.git = "https://github.com/kawarimidoll/rustmigemo.git"
src.branch = "fix-build-error-in-non-x86"

[treesitter-ls]
fetch.github = "atusy/treesitter-ls"
src.manual = "v0.0.2"

[plamo-translate]
fetch.github = "pfnet/plamo-translate-cli"
src.manual = "1.0.5"

[stormy]
fetch.github = "ashish0kumar/stormy"
src.manual = "v0.3.3"

[lolcrab]
fetch.github = "mazznoer/lolcrab"
src.manual = "v0.4.1"

[rxpipes]
fetch.github = "inunix3/rxpipes"
src.manual = "v1.3.0"
