[difit]
fetch.github = "yoshiko-pg/difit"
src.manual = "v2.2.7"

[ghost]
fetch.github = "skanehira/ghost"
src.manual = "v0.3.0"

[jsmigemo]
fetch.url = "https://registry.npmjs.org/jsmigemo/-/jsmigemo-$ver.tgz"
src.manual = "0.4.8"

[treesitter-ls]
fetch.github = "atusy/treesitter-ls"
src.manual = "v0.0.2"
